### ISSUE TITLE
cxml-location?

### ISSUE THREAD

**Issue by xach** [scymtym/jenkins#1]
I wanted to try this out, but I don't have cxml-location or know where it is. Where can I find it?

**Comment by scymtym** [comment]
The `jenkins` system is not ready for use yet. I had to push early because of the holidays.

`cxml-location` provides bindings and type conversions for XPath-based locations in XML documents. I will probably push it soon (there is one more dependency issue). I will close this issue then.

**Comment by scymtym** [comment]
Xach, the missing system is now available as scymtym/xml.location. `jenkins` is still unfinished, of course, but should work when tpapp/let-plus#4 is available.

I can already use it with https://ci.jenkins-ci.org/ and https://ci.cor-lab.org (the latter requires authentication for some things).

**Comment by scymtym** [comment]
@xach This has been superseeded by something else in a different repository. Drop me a line if you are still interested in the general idea.
